# -----------------------------------------------------------------------------
# Package Manifest
# -----------------------------------------------------------------------------
packages:
  native:
    arch:
      - base-devel
      - pacman-contrib
    debian:
      - build-essential
    pop:
      - build-essential
    darwin:
      - coreutils
  
  # Packages with consistent names across Arch (Pacman), Debian (APT), and macOS (Brew)
  universal:
    - curl
    - git
    - zsh
    - fzf
    - zoxide
    - micro
    - btop
    - ripgrep
    - fd-find

  # Role-specific packages (mapped in the install script)
  roles:
    desktop:
      - hyprland
    laptop:
      - brightnessctl
    server:
      - htop

# -----------------------------------------------------------------------------
# Standalone Binaries (GitHub Releases)
# -----------------------------------------------------------------------------
# These are used by Section 4 of the install script to download tools 
# not available in standard APT/Pacman repos.
binaries:
  - name: lazygit
    repo: jesseduffield/lazygit
    pattern: "Linux_x86_64\\.tar\\.gz"
  - name: btm
    repo: ClementTsang/bottom
    pattern: "x86_64-unknown-linux-gnu\\.tar\\.gz"
  - name: eza
    repo: eza-community/eza
    pattern: "x86_64-unknown-linux-gnu\\.tar\\.gz"
    
# -----------------------------------------------------------------------------
# User Information
# -----------------------------------------------------------------------------
name: "Frank Chen"
email: "frank.chen@gmail.com"
